import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { createServer } from '../server.mjs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const server = createServer();
await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
const base = `http://127.0.0.1:${server.address().port}`;
let browser;
const report = { widths:[], checks:[], errors:[] };
await mkdir('artifacts',{recursive:true});
try {
  browser = await chromium.launch({channel:'msedge',headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  page.on('pageerror', error => report.errors.push(error.message));
  page.on('console', message => { if(message.type()==='error') report.errors.push(message.text()); });
  page.on('response', response => { if(response.status()>=400) report.errors.push(`${response.status()} ${response.url()}`); });
  await page.goto(base);
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('h1').count(),1);
  assert.equal(await page.locator('#main > section').count(),7);
  await page.locator('.portrait img').scrollIntoViewIfNeeded();
  await page.locator('.portrait img').evaluate(img=>img.decode());
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
  await page.locator('#home').screenshot({path:'artifacts/hero.png'});
  await page.locator('#about').screenshot({path:'artifacts/about.png'});
  for (const width of [320,375,400,768,1024,1440]) {
    await page.setViewportSize({width,height:900});
    const sizes=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
    if(sizes.scroll>sizes.width+1) console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(el=>el.getBoundingClientRect().right>innerWidth+1).map(el=>({tag:el.tagName,cls:el.className,right:el.getBoundingClientRect().right,width:el.getBoundingClientRect().width})).slice(0,20)));
    assert.ok(sizes.scroll<=sizes.width+1,`Переполнение ${width}: ${sizes.scroll}`);report.widths.push(sizes);
  }
  report.checks.push('Ширины 320, 375, 400, 768, 1024, 1440 без переполнения');
  const anchors=await page.locator('a[href^="#"]').evaluateAll(links=>links.map(a=>({href:a.getAttribute('href'),exists:!!document.getElementById(a.getAttribute('href').slice(1))})));
  assert.ok(anchors.every(a=>a.exists),'Якорь без целевого раздела');
  report.checks.push('Все внутренние якоря имеют целевые разделы');
  await page.emulateMedia({reducedMotion:'reduce'});
  for(const id of ['work','services','process','about','contact']){
    await page.locator('#navigation a[href="#'+id+'"]').first().click();
    assert.equal(new URL(page.url()).hash,'#'+id);
    const top=await page.locator('#'+id).evaluate(el=>el.getBoundingClientRect().top);
    assert.ok(top>=-1 && top<180, 'Якорь '+id+' прокручивает страницу');
  }
  await page.emulateMedia({reducedMotion:'no-preference'});
  report.checks.push('Переходы навигации к пяти секциям');
  for(const width of [320,375,400,768,1024,1440]){
    await page.setViewportSize({width,height:900});
    const small=await page.locator('a,button,summary').evaluateAll(elements=>elements.filter(el=>el.getClientRects().length && getComputedStyle(el).visibility!=='hidden').filter(el=>{const r=el.getBoundingClientRect();return r.width<43.5||r.height<43.5}).map(el=>el.textContent.trim()));
    assert.deepEqual(small,[], 'Область нажатия меньше 44px на '+width);
  }
  report.checks.push('Видимые ссылки, кнопки и summary не меньше 44 × 44 на шести ширинах');
  await page.setViewportSize({width:320,height:812});
  const originalTitle=await page.locator('h1').innerHTML();
  await page.locator('h1').evaluate(el=>el.textContent='Сверхдлинноеназваниецифровогопроектабезпробеловдляпроверкипереноса');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Длинное слово в заголовке выходит за экран');
  await page.locator('h1').evaluate((el,html)=>el.innerHTML=html,originalTitle);
  report.checks.push('Длинное слово в заголовке на 320px');
  await page.setViewportSize({width:375,height:812});
  await page.goto(base);
  await page.evaluate(()=>document.fonts.ready);
  await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
  await page.screenshot({path:'artifacts/mobile-hero.png'});
  const menu=page.getByRole('button',{name:'Меню'});
  await menu.click();assert.equal(await menu.getAttribute('aria-expanded'),'true');
  await page.keyboard.press('Escape');assert.equal(await menu.getAttribute('aria-expanded'),'false');
  assert.equal(await menu.evaluate(el=>el===document.activeElement),true);
  await menu.click();await page.locator('#navigation').getByRole('link',{name:'Работы',exact:true}).click();assert.equal(await menu.getAttribute('aria-expanded'),'false');
  await page.setViewportSize({width:1440,height:1000});assert.equal(await page.locator('#navigation').isVisible(),true);
  report.checks.push('Мобильное меню, Escape, возврат фокуса, выбор ссылки, переход на широкий экран');
  await page.getByRole('button',{name:'Приложение для команды'}).click();assert.equal(await page.locator('#demo-goal').textContent(),'Организовать работу');
  await page.getByRole('button',{name:'Автоматизация заявок'}).click();assert.equal(await page.locator('#demo-goal').textContent(),'Подготовить бриф');
  await page.getByRole('button',{name:'Сайт эксперта',exact:false}).click();assert.equal(await page.locator('#demo-goal').textContent(),'Представить экспертизу');
  report.checks.push('Три сценария демонстрации');
  await page.locator('.faq-list summary').first().focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.faq-list details').first().getAttribute('open'),'');
  report.checks.push('Раскрытие ответа с клавиатуры');
  await page.evaluate(()=>{window.testEvents=[];window.addEventListener('landing:analytics',e=>window.testEvents.push(e.detail));});
  let posts=0;page.on('request',request=>{if(request.method()==='POST')posts++;});
  await page.getByRole('button',{name:'Проверить заполнение'}).click();assert.equal(await page.locator('#contact-input').getAttribute('aria-invalid'),'true');
  await page.locator('#contact-input').fill('@test_contact');await page.locator('#task-input').fill('Нужен сайт для консультаций');
  await page.getByRole('button',{name:'Проверить заполнение'}).click();
  assert.match(await page.locator('#form-status').textContent(),/не отправлено/);assert.equal(posts,0);
  assert.equal(await page.locator('#task-input').inputValue(),'Нужен сайт для консультаций');
  const events=await page.evaluate(()=>window.testEvents);assert.ok(events.every(e=>e.name!=='generate_lead'));assert.doesNotMatch(JSON.stringify(events),/@test_contact|Нужен сайт/);
  assert.ok(await page.locator('a[href="https://t.me/Mari_APecherskaya"]').count()>=2);
  report.checks.push('Ошибки, сохранение ввода, предпросмотр без запроса и лида, события без личных данных, Telegram');
  await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');
  report.checks.push('Уменьшенное движение');
  // Browser zoom halves the CSS viewport; body.style.zoom does not update media queries.
  await page.setViewportSize({width:384,height:450});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Переполнение при эквивалентном узком окне');
  report.checks.push('Перекомпоновка в окне 384px (эквивалент 768px при 200%); нативный масштаб отдельно не проверялся');
  const liveContext=await browser.newContext();
  await liveContext.route('**/config.js',route=>route.fulfill({contentType:'text/javascript',body:'export const config = {leadEndpoint:"/api/lead"};'}));
  let release;let livePosts=0;
  await liveContext.route('**/api/lead',async route=>{livePosts++;await new Promise(resolve=>release=resolve);await route.fulfill({status:503,contentType:'application/json',body:'{"ok":false}'});});
  const livePage=await liveContext.newPage();await livePage.goto(base);
  await livePage.locator('#contact-input').fill('@test');await livePage.locator('#task-input').fill('Проверка обработки ошибки');
  await livePage.getByRole('button',{name:'Отправить задачу',exact:true}).click();
  await livePage.waitForFunction(()=>document.querySelector('#contact-form').getAttribute('aria-busy')==='true');
  assert.equal(await livePage.locator('.form-submit').isDisabled(),true);
  await livePage.waitForTimeout(100);release();
  await livePage.locator('#form-status').filter({hasText:'Не удалось'}).waitFor();
  assert.equal(await livePage.locator('#task-input').inputValue(),'Проверка обработки ошибки');assert.equal(livePosts,1);
  await liveContext.unroute('**/api/lead');
  await liveContext.route('**/api/lead',route=>route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'}));
  await livePage.evaluate(()=>{window.events=[];addEventListener('landing:analytics',e=>window.events.push(e.detail));});
  await livePage.getByRole('button',{name:'Отправить задачу',exact:true}).click();
  await livePage.locator('#form-status').filter({hasText:'Задача отправлена'}).waitFor();
  assert.equal(await livePage.locator('.form-submit').isDisabled(),true);
  assert.equal(await livePage.evaluate(()=>window.events.filter(e=>e.name==='generate_lead').length),1);
  await livePage.locator('#task-input').fill('Изменённая задача для сайта');assert.equal(await livePage.locator('.form-submit').isDisabled(),false);
  report.checks.push('При подмене службы: блокировка во время запроса, 503 сохраняет ввод, подтверждение даёт один лид и блокирует повтор');
  const nojs = await browser.newContext({javaScriptEnabled:false,viewport:{width:375,height:812}});
  const staticPage = await nojs.newPage();await staticPage.goto(base);
  assert.equal(await staticPage.locator('#navigation').isVisible(),true);
  assert.equal(await staticPage.getByRole('button',{name:'Проверить заполнение'}).isDisabled(),true);
  await staticPage.locator('.faq-list summary').first().click();assert.equal(await staticPage.locator('.faq-list details').first().getAttribute('open'),'');
  assert.equal(await staticPage.locator('#alternate-contacts a').first().isVisible(),true);
  report.checks.push('Без JavaScript: навигация, ответы и Telegram работают; форма не отправляет данные');
  assert.deepEqual(report.errors,[]);
  console.log(JSON.stringify(report,null,2));
  await writeFile('artifacts/browser-report.json',JSON.stringify(report,null,2));
} finally {await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
